### PR TITLE
added support for multiline msgctxt strings

### PR DESCRIPTION
**Pull request by tafkanator**
added support for multiline msgctxt files

https://github.com/rubenv/pofile/issues/23

### CODE REVIEW

**Comment by rubenv** [comment]
Could you add a test case?

**Comment by tafkanator** [comment]
I added test case. One thin i noted is that "C-Strings: should write identical file after parsing a file" fails on my local environment. I did not investigate, but i think it's because i am working on Windows machine and line breaks are different between `toString` and original version

**Comment by rubenv** [comment]
Cool, thanks!

> i think it's because i am working on Windows machine and line breaks are different between toString and original version

That's a different issue then, shouldn't block this merge.

**Comment by rubenv** [comment]
Released to NPM as `v1.0.10`.

**Pull request merged**
