### PR TITLE
Fixed issue with plural multi line text.

### PR DESCRIPTION
**Pull request by janhommes**
The following .po file content leads to wrong parsing:
```
# plural text must suport \n
msgid ""
"Test.\n"
" multiline."
msgid_plural ""
"Test\n"
" multiline plural."
msgstr[0] ""
"Test.\n"
" mehrzeilig."
msgstr[1] ""
"Test.\n"
" mehrzeilig Plural."
```
The result before this fix for msgstr[1] was `","Test."," mehrzeilig Plural.` instead of `Test\n. mehrzeilig Plural.`. With this pull request this bug is gone.

### CODE REVIEW

**Comment by rubenv** [comment]
Could you add a unit test that breaks without the fix? Just to prevent regressions.

**Comment by janhommes** [comment]
Actual [this](https://github.com/rubenv/pofile/blob/cfe01e8aea46f50a21b338d25a48f591483bd334/test/write.js#L474) test fails with the new content in the .po before this fix.

**Comment by rubenv** [comment]
Oh yes, I see, perfect!

Thanks!

**Comment by rubenv** [comment]
Released to NPM as `v1.0.9`.

**Pull request merged**
