### PR TITLE
Add support for the typescript projects and IDE-s.

### PR DESCRIPTION
**Pull request by ma2ciek**
This PR adds support for the typescript projects and IDE-s which supports TS, for example VS-Code.

ame_17 42 38

I would be happy if you could merge it :)

Thanks,
Maciek.

### CODE REVIEW

**Comment by rubenv** [comment]
Cool!

I have no clue if this is correct or not, since I don't know Typescript, so I'll just go ahead and merge it.

**Comment by rubenv** [comment]
Published to NPM as `v1.0.6`. Thanks!

**Comment by megaboich** [comment]
Dear @ma2ciek ,
I have troubles while using your Typescript definitions.

When I do import statement I have error like this, both in VSCode and command line:
screen1

I also tried this style but with the same result.
```
import * as pofile from 'pofile'
```

So, I inspected `pofile.d.ts` and just noticed that it has some different style that I am used to. I did comparison with other `d.ts` files for example from `moment` package and it is really in different format.

I tried to update `pofile.d.ts` and it works, see this: [Gist](https://gist.github.com/megaboich/f8c2dd8fb8b8664d8330848c1a3f9064)
So I can import package like this:
```
import * as pofile from 'pofile'
...

    for (const poFile of poFiles) {
        const poContent = fs.readFileSync(poFile, "utf-8");
        const poFileParsed = pofile.parse(poContent);
        console.log(`file ${poFile}, items: ${poFileParsed.items.length}`)
    }
```

I use Typescript version 2.2.2, just in case.
Do you have examples how to import your definitions? Or do you think it is reasonable to create pull request to update your definitions?

Thanks,
Oleksandr.

**Comment by ma2ciek** [comment]
Thanks for reporting this issue @megaboich

Probably your declaration file is better. Mine should work with `import PO from 'pofile';` syntax, as I was trying to make it work inside the JS file with the CommonJS syntax (`const PO = require( 'pofile' )`. I didn't know even, that you can declare module as a namespace and import it with ES6 import syntax, so I learned something from you ;) (I'm still a little bit confused about the available options in import / export in the `d.ts` files)

If your compiled JS code works with this declaration file, feel free to make a PR.
Maciek.

**Comment by megaboich** [comment]
Thanks @ma2ciek for your quick response.
I've created pull request https://github.com/rubenv/pofile/pull/29
Could you please verify that it works for you?

**Pull request merged**
