### PR TITLE
Add proper support for no headers in po files

### PR DESCRIPTION
**Pull request by johnyb**
This is still WIP, because the examples are not handled correctly, yet.

### CODE REVIEW

**Comment by johnyb** [comment]
Once, all the examples are working, I guess #18 can be closed.

**Comment by johnyb** [comment]
I changed the fixing commit to also handle the edge cases, when no header is present. Tests are green, again.

**Comment by rubenv** [comment]
Looks good!

**Comment by rubenv** [comment]
Released `1.0.2`. Thanks!

**Pull request merged**
